### ISSUE TITLE
Fundargerðir Framkvæmdaráðs

### ISSUE THREAD

**Issue by thorlaug** [piratar/piratar.is#62]
Fundargerðir framkvæmdaráðs í sjálfvirki birtingu hér
http://piratar.is/um-pirata/bokhald-og-rekstur/framkvaemdarad/

þarna eiga að birtast fundargerðir í tímaröð, einhver villa núna sem birtir ekki fundargerðir júní, júlí, ágúst sem þó eru virkar inni í kerfinu.

Elections 2016 #Elections2016 #HighPriority

**Comment by thorlaug** [comment]
Þessi fundargerð birtist svört

http://piratar.is/fundargerdir/framkvaemdarad/fundur-framkvaemdarads-6-september-2016/

**Comment by thorlaug** [comment]
Þetta vandamál er enn til staðar á þessari síðu 
http://piratar.is/um-pirata/bokhald-og-rekstur/fundargerdir/

**Comment by thorlaug** [comment]
félagsmenn farnir að kvarta yfir að fundargerðirnar vanti

**Comment by helgihg** [comment]
Fixed with commit 3dcb1f70dbfd691a9cb062ace345b5dc60a38600.

From commit comment:
IMPORTANT: Save-format of custom field "dagsetning_fundar" undir "fundargerdir" had to be changed from "dd/mm/yy" to "yy-mm-dd" and corresponding data had to be updated with the following SQL:

UPDATE wpir4t4r_postmeta
SET
    meta_value = STR_TO_DATE(meta_value, '%d/%m/%Y')
WHERE
    meta_key = 'dagsetning_fundar'
    AND meta_value LIKE '__/__/____'
